module.exports = [
  {
    type: "copula",
    elements: [
      "is",
      "are",
      "was",
      "were",
      "be",
      "appears",
      "appears to be",
      "appears as",
      "become",
      "becomes",
      "constitute",
      "constitutes",
      "proves to be",
      "seems",
      "seems to be"
    ]
  },
  {
    type: "coordinating conjunction",
    elements: ["and", "or", "but", "nor", "so", "for", "yet"]
  },
  {
    type: "subordinating conjunction",
    elements: [
      "after",
      "although",
      "as",
      "as if",
      "as long as",
      "as much as",
      "as soon as",
      "as though",
      "assuming that",
      "because",
      "before",
      "by the time",
      "even if",
      "even though",
      "how",
      "if",
      "in case",
      "in case",
      "in case that",
      "in order that",
      "in order to",
      "lest",
      "now that",
      "once",
      "only if",
      "provided that",
      "rather than",
      "since",
      "so that",
      "than",
      "that",
      "though",
      "till",
      "unless",
      "until",
      "what",
      "whatever",
      "when",
      "whenever",
      "where",
      "whereas",
      "wherever",
      "whether",
      "which",
      "whichever",
      "while",
      "who",
      "whoever",
      "whom",
      "whomever",
      "whose",
      "why"
    ]
  }
]
